#!/bin/sh
set -x
set -e


# for initramfs-tools hook-functions
export WORKDIR=$(mktemp -d --suffix=.ubuntu-core-initramfs)
export DESTDIR=$WORKDIR/main
export EARLYDIR=$WORKDIR/early
export verbose=n
# for /usr/lib/dracut/dracut-install
export DESTROOTDIR=$DESTDIR

# our boot sequence is to be controled by systemd
. /usr/share/initramfs-tools/hook-functions

# install everything
cp -ar install-tmp/* $DESTDIR

export version=${version-$(uname -r)}
export MODULESDIR="/lib/modules/${version}"
auto_add_modules base block scsi
manual_add_modules $(cat modules.txt)
for f in $MODULESDIR/modules.*; do
	copy_file conf $f $f
done

sudo rm -f ubuntu-core-initramfs.img

# create initrd
cd $DESTDIR
find . | cpio --create --format='newc' --owner=0:0 | lz4 -9 -l > $OLDPWD/ubuntu-core-initramfs.img
cd $OLDPWD
