#!/bin/sh
o=/sysroot/writable/system-data/var/lib/snapd/modeenv
sed 's/.*snapd_recovery_mode=\([a-z]*\).*/mode=\1/' /proc/cmdline >> $o
sed 's/.*snapd_recovery_system=\([0-9]*\).*/recovery_system=\1/' /proc/cmdline >> $o
mount -o bind /run/mnt/ubuntu-seed/boot/grub /sysroot/boot/grub

