#!/bin/sh
set -e

# Run snap-bootstrap
cmd="systemd-mount --no-pager --no-ask-password "
/usr/lib/snapd/snap-bootstrap initramfs-mounts | sed "s/^/$cmd/" > /root/bootstrap.cmds.$1
set +e
. /root/bootstrap.cmds.$1
set -e

mkdir -p /run/systemd/system/initrd-fs.target.d
cat >/run/systemd/system/initrd-fs.target.d/core.conf <<EOF
[Unit]
Requires=populate-writable.service
After=populate-writable.service
EOF
cp -r /run/systemd/system/initrd-fs.target.d /run/systemd/system/initrd.target.d
cp -r /run/systemd/system/initrd-fs.target.d /run/systemd/system/initrd-switch-root.target.d

