#!/bin/sh
set -e
cmd="systemd-mount --no-block --no-pager --no-ask-password"
# Mount base
$cmd /run/mnt/ubuntu-seed/snaps/core20_*.snap /sysroot -pBefore=initrd-cleanup.target
cp /run/systemd/transient/*.mount /etc/systemd/system
# Mount writable
$cmd --type=tmpfs tmpfs /sysroot/writable -pAfter=sysroot.mount -pRequires=sysroot.mount -pWants=populate-writable.service -pBefore=initrd-cleanup.target
cp /run/systemd/transient/*.mount /etc/systemd/system
# Mount kernel
$cmd /run/mnt/ubuntu-seed/snaps/pc-kernel_*.snap /run/mnt/kernel -pBefore=initrd-cleanup.target
cp /run/systemd/transient/*.mount /etc/systemd/system
# Bind-mount things (Possibly core should be handling this!, or like code in a kernel snap)
# chroot/call handle-writable paths
#$cmd --type=none --options=bind /run /sysroot/run
#/sysroot/usr/lib/core/handle-writable-paths /sysroot
#$cmd --umount /sysroot/run
