#!/bin/sh
set -e

# Run snap-bootstrap
cmd="systemd-mount --no-pager --no-ask-password "
pass=0
while true; do
    needed="$(/usr/lib/snapd/snap-bootstrap initramfs-mounts)"
    if [ -z "$needed" ]; then
       break
    fi
    echo "$needed" | sed "s/^/$cmd/" > "/root/bootstrap.cmds.$pass"
    set +e
    . /root/bootstrap.cmds.$pass
    set -e
    pass=$((pass + 1))
done

mkdir -p /run/systemd/system/initrd-fs.target.d
cat >/run/systemd/system/initrd-fs.target.d/core.conf <<EOF
[Unit]
Requires=populate-writable.service
After=populate-writable.service
EOF
cp -r /run/systemd/system/initrd-fs.target.d /run/systemd/system/initrd.target.d
cp -r /run/systemd/system/initrd-fs.target.d /run/systemd/system/initrd-switch-root.target.d

