lib/systemd/systemd-bless-boot
lib/systemd/system-generators/systemd-bless-boot-generator
lib/systemd/system/sysinit.target.wants/systemd-boot-system-token.service
lib/systemd/system/systemd-bless-boot.service
lib/systemd/system/systemd-boot-system-token.service
lib/systemd/system/systemd-boot-update.service
usr/bin/bootctl
usr/share/bash-completion/completions/bootctl
../extra/initramfs etc/
../extra/kernel etc/
