#!/bin/sh
set -e

version="$1"
command -v ubuntu-core-initramfs >/dev/null 2>&1 || exit 0

# avoid running multiple times
if [ -n "$DEB_MAINT_PARAMS" ]; then
	eval set -- "$DEB_MAINT_PARAMS"
	if [ -z "$1" ] || [ "$1" != "configure" ]; then
		exit 0
	fi
fi

# do not clobber pre-signed .efi
if [ -e /boot/kernel.efi-$version ]; then
    exit 0
fi

# Note focal's systemd & objcopy fail on arm64
# Do not enable arm64, regressed twice now
case `dpkg --print-architecture` in
    amd64)
	case $version in
	    *-azure-fde)
		ubuntu-core-initramfs create-initrd --feature main server cloudimg-rootfs --kernelver $version
		# Currently nullboot doesn't seal cmdline, thus it must be baked in for azure
		ubuntu-core-initramfs create-efi --unsigned --kernelver $version --cmdline "snapd_recovery_mode=cloudimg-rootfs console=tty1 console=ttyS0 earlyprintk=ttyS0"
		;;
	    *)
		ubuntu-core-initramfs create-initrd --kernelver $version
		ubuntu-core-initramfs create-efi --unsigned --kernelver $version
		;;
	esac
	;;
    *)
	ubuntu-core-initramfs create-initrd --kernelver $version
	;;
esac

