#!/bin/sh
set -e

version="$1"
command -v ubuntu-core-initramfs >/dev/null 2>&1 || exit 0

# avoid running multiple times
#if [ -n "$DEB_MAINT_PARAMS" ]; then
#	eval set -- "$DEB_MAINT_PARAMS"
#	if [ -z "$1" ] || [ "$1" != "configure" ]; then
#		exit 0
#	fi
#fi

# do not clobber pre-signed .efi
#if [ -e /boot/kernel.efi-$version ]; then
#    exit 0
#fi

ubuntu-core-initramfs create-initrd --kernelver $version --feature main server cloudimg-rootfs-draft-1

case `dpkg --print-architecture` in
    amd64)
        ubuntu-core-initramfs create-efi --kernelver $version --cmdline 'snapd_recovery_mode=run-cloudimg-rootfs-draft-1 dangerous'
        ;;
esac
cp /boot/kernel.efi-$version /boot/efi/EFI/ubuntu/grubx64.efi

