#!/bin/sh
set -e

version="$1"
command -v ubuntu-core-initramfs >/dev/null 2>&1 || exit 0

# avoid running multiple times
if [ -n "$DEB_MAINT_PARAMS" ]; then
	eval set -- "$DEB_MAINT_PARAMS"
	if [ -z "$1" ] || [ "$1" != "configure" ]; then
		exit 0
	fi
fi

ubuntu-core-initramfs create-initrd --kernelver $version

if [ `dpkg --print-architecture` = 'amd64' ]; then
    ubuntu-core-initramfs create-efi --kernelver $version
fi
