#!/bin/sh

mode="$(/usr/libexec/core/get-mode mode)" || mode="$(/usr/libexec/core/get-arg snapd_recovery_mode)" || mode="run"

if [ "${mode}" = "run" ]; then
    # remove any previous overrides
    rm -rf /run/systemd/journald.conf.d/core-override.conf
    exit 0
fi

mkdir -p /run/systemd/journald.conf.d
echo [Journal] >> /run/systemd/journald.conf.d/core-override.conf
echo ForwardToConsole=true >> /run/systemd/journald.conf.d/core-override.conf
