#!/bin/sh

set -eu

if [ "$(/usr/libexec/core/get-arg snapd_recovery_mode || true)" != install ]; then
    exit 0
fi

mkdir -p /run/systemd/journald.conf.d
cat <<EOF >/run/systemd/journald.conf.d/core-override.conf
[Journal]
ForwardToConsole=true
EOF
