#!/bin/sh

set -eu

if [ "$(/usr/libexec/core/get-arg snapd_recovery_mode || true)" != run ]; then
    exit 0
fi

mkdir -p "${1}"

cat <<EOF >"${1}/run-mnt-data.mount"
[Unit]
BindsTo=dev-ubuntu-data.device
After=dev-ubuntu-data.device

[Mount]
Type=ext4
What=/dev/ubuntu/data
Where=/run/mnt/data
EOF

cat <<EOF >"${1}/run-mnt-ubuntu\\x2dsave.mount"
[Unit]
BindsTo=dev-ubuntu-save.device
After=dev-ubuntu-save.device

[Mount]
Type=ext4
What=/dev/ubuntu/save
Where=/run/mnt/ubuntu-save
EOF

cat <<EOF >"${1}/run-mnt-ubuntu\\x2dseed.mount"
[Unit]
BindsTo=dev-ubuntu-seed.device
After=dev-ubuntu-seed.device

[Mount]
Type=vfat
What=/dev/ubuntu/seed
Where=/run/mnt/ubuntu-seed
EOF

cat <<EOF >"${1}/run-mnt-ubuntu\\x2dboot.mount"
[Unit]
BindsTo=dev-ubuntu-boot.device
After=dev-ubuntu-boot.device

[Mount]
Type=ext4
What=/dev/ubuntu/boot
Where=/run/mnt/ubuntu-boot
EOF

mkdir -p "${1}/initrd-root-fs.target.wants"
mkdir -p "${1}/initrd-root-fs.target.requires"

ln -s "../run-mnt-ubuntu\\x2dseed.mount" "${1}/initrd-root-fs.target.wants/run-mnt-ubuntu\\x2dseed.mount"
ln -s "../run-mnt-ubuntu\\x2dboot.mount" "${1}/initrd-root-fs.target.requires/run-mnt-ubuntu\\x2dboot.mount"
ln -s "../run-mnt-data.mount" "${1}/initrd-root-fs.target.requires/run-mnt-data.mount"
ln -s "../run-mnt-ubuntu\\x2dsave.mount" "${1}/initrd-root-fs.target.wants/run-mnt-ubuntu\\x2dsave.mount"
