#!/bin/sh

set -eu

normaldir="${1}"
mkdir -p "${normaldir}"

generate_unit() {
    where="${1}"
    fs="${2}"
    device="${3}"
    shift 2

    mount_unit="$(systemd-escape --suffix=mount -p "${where}")"

    case "${fs}" in
        tmpfs)
            cat <<EOF >"${normaldir}/${mount_unit}"
[Unit]

[Mount]
Type=${fs}
What=${device}
Where=${where}
Options=nosuid,private
EOF
            ;;
        *)
            device_escaped="$(systemd-escape -p "${device}")"
            cat <<EOF >"${normaldir}/${mount_unit}"
[Unit]
BindsTo=${device_escaped}.device
After=${device_escaped}.device
Requires=systemd-fsck@${device_escaped}.service
After=systemd-fsck@${device_escaped}.service

[Mount]
Type=${fs}
What=${device}
Where=${where}
Options=private
EOF
            ;;
    esac


    for target; do
        mkdir -p "${normaldir}/${target}"
        ln -s "../${mount_unit}" "${normaldir}/${target}/${mount_unit}"
    done
}

if mode="$(/usr/libexec/core/get-arg snapd_recovery_mode)"; then
  case "${mode}" in
      run)
          generate_unit /run/mnt/data ext4 /dev/ubuntu/data initrd-root-fs.target.requires
          generate_unit /run/mnt/ubuntu-seed vfat /dev/ubuntu/seed initrd-root-fs.target.wants
          generate_unit /run/mnt/ubuntu-boot ext4 /dev/ubuntu/boot initrd-root-fs.target.requires model-available.target.requires
          generate_unit /run/mnt/ubuntu-save ext4 /dev/ubuntu/save initrd-root-fs.target.wants
          ;;
      install)
          generate_unit /run/mnt/ubuntu-seed vfat /dev/ubuntu/seed initrd-root-fs.target.requires model-available.target.requires
          generate_unit /run/mnt/data tmpfs tmpfs initrd-root-fs.target.requires
          ;;
      *)
          exit 0
          ;;
  esac
fi
